name: Compilar APK con Flet

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flet-dev/flet-build:latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Compilar APK
        run: |
          flet build apk

      - name: Subir el archivo APK
        uses: actions/upload-artifact@v4
        with:
          name: tabata-app-apk
          path: build/apk/*.apk
